# Estudo da biblioteca Pandas

# 1. Carregue suas ferramentas

In [1]:
# Importar biblioteca Pandas
import pandas as pd

In [2]:
# Importar o dataset
#dataset = pd.read_csv('nome_tabela.csv', sep=',', skiprows=None)

dataset = pd.read_excel('tabela.xlsx')
dataset

# pd.DataFrame(): cria um DataFrame a partir de uma lista de listas ou uma matriz.
# pd.read_excel(): importa um arquivo Excel para um DataFrame.

#  O (sep=',') é colocado para indicar qual o separador de dados
# neste caso, o csv já esta separando os dados por ',', portanto o (sep=',') não era necessário. Foi colocado para fins didáticos.

,esta tabela foi desenvolvida para fins educativos,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,nome,sobrenome,idade,sexo,altura,salario_mensal,profissão
1,João,Silva,30,M,"1,64m",7000,Engenheiro
2,Lara,bembo,29,F,"1,64m",3500,Músico
3,Pedro,bembo,35,M,"1,67m",NaN,Advogado
4,Monica,Santos,28,F,"1,66m",3500,Músico
5,Larissa,Ferreira,31,F,"1,8m",3500,Professor
6,Lara,bembo,30,F,"1,62m",7000,Engenheiro
7,Pedro,Lima,35,M,"1,65m",7000,Engenheiro
8,Marcos,Lima,45,M,"1,64m",4500,Engenheiro
9,Ana,Souza,27,F,"1,75m",6000,Professor
10,José,bembo,35,M,"1,9m",3500,Editor
11,Monica,Ferreira,30,F,"1,62m",NaN,Editor
12,Ana,lokuto,27,F,"1,67m",5000,Advogado
13,Jurema,Silva,32,F,"1,65m",3500,Advogado
14,Pedro,Lima,34,M,"1,7m",4500,Editor
15,Flávio,Silva,31,M,"1,64m",3500,Engenheiro
16,André,Ferreira,35,M,"1,72m",6000,Engenheiro
17,José,Ferreira,45,M,"1,72m",4500,Músico
18,Pedro,bembo,30,M,"1,69m",3500,Músico
19,Pedro,Souza,29,M,"1,64m",NaN,Editor
20,Augusto,lokuto,40,M,"1,66m",6000,Músico
21,José,Santos,40,M,"1,66m",7000,Editor
22,Flávio,Souza,35,M,"1,69m",7000,Advogado
23,Ana,Lima,29,F,"1,64m",5000,Professor
24,Flávio,Souza,NaN,NaN,NaN,7000,Músico
25,Flávio,Souza,45,M,"1,64m",7000,Músico
26,Pedro,lokuto,29,M,"1,67m",4500,Professor
27,Monica,Lima,32,F,"1,65m",6000,Engenheiro
28,Monica,bembo,34 anos,F,"1,66m",7000,Professor
29,Joana,Ferreira,31,F,"1,75m",5000,Engenheiro
30,Flávio,bembo,27,M,"1,66m",3500,Professor
31,Augusto,Mezenga,27,M,"1,62m",4500,Engenheiro
32,Pedro,Berdinatz,29,M,"1,72m",3500,Editor
33,Lara,Santos,28,Feminino,"1,7m",5000,Engenheiro
34,Pedro,Souza,35,M,"1,72m",5000,Engenheiro
35,Pedro,Souza,35,M,"1,72m",5000,Engenheiro
36,esta tabela termina bem aqui,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Define configuracões padrões do Pandas
# max_colwidth=40: Limita a largura das colunas a 40 caracteres.

pd.set_option('max_colwidth', 40)
pd.get_option('max_colwidth')

40

# 3. Limpando os dados

Precisamos definir as colunas, definir os data types, eliminar valores nulos e duplicadas, linhas de cabecalho e footer.

## 3.1 Eliminando cabecalhos e Footer

In [4]:
#eliminamos a primeira linha com o comando skiprows, ao carregar.
#tambem poderia ser usado o drop: dataset.drop(dataset.index[1], inplace=True)
## O inplace modifica o datadrame original, sendo possível trabalhar
#com o mesmo dataframe modificado nos comandos posteriores e não apenas nesse

dataset = pd.read_excel('tabela.xlsx', skiprows= 1)
dataset

,nome,sobrenome,idade,sexo,altura,salario_mensal,profissão
0,João,Silva,30,M,"1,64m",7000.0,Engenheiro
1,Lara,bembo,29,F,"1,64m",3500.0,Músico
2,Pedro,bembo,35,M,"1,67m",NaN,Advogado
3,Monica,Santos,28,F,"1,66m",3500.0,Músico
4,Larissa,Ferreira,31,F,"1,8m",3500.0,Professor
5,Lara,bembo,30,F,"1,62m",7000.0,Engenheiro
6,Pedro,Lima,35,M,"1,65m",7000.0,Engenheiro
7,Marcos,Lima,45,M,"1,64m",4500.0,Engenheiro
8,Ana,Souza,27,F,"1,75m",6000.0,Professor
9,José,bembo,35,M,"1,9m",3500.0,Editor
10,Monica,Ferreira,30,F,"1,62m",NaN,Editor
11,Ana,lokuto,27,F,"1,67m",5000.0,Advogado
12,Jurema,Silva,32,F,"1,65m",3500.0,Advogado
13,Pedro,Lima,34,M,"1,7m",4500.0,Editor
14,Flávio,Silva,31,M,"1,64m",3500.0,Engenheiro
15,André,Ferreira,35,M,"1,72m",6000.0,Engenheiro
16,José,Ferreira,45,M,"1,72m",4500.0,Músico
17,Pedro,bembo,30,M,"1,69m",3500.0,Músico
18,Pedro,Souza,29,M,"1,64m",NaN,Editor
19,Augusto,lokuto,40,M,"1,66m",6000.0,Músico
20,José,Santos,40,M,"1,66m",7000.0,Editor
21,Flávio,Souza,35,M,"1,69m",7000.0,Advogado
22,Ana,Lima,29,F,"1,64m",5000.0,Professor
23,Flávio,Souza,NaN,NaN,NaN,7000.0,Músico
24,Flávio,Souza,45,M,"1,64m",7000.0,Músico
25,Pedro,lokuto,29,M,"1,67m",4500.0,Professor
26,Monica,Lima,32,F,"1,65m",6000.0,Engenheiro
27,Monica,bembo,34 anos,F,"1,66m",7000.0,Professor
28,Joana,Ferreira,31,F,"1,75m",5000.0,Engenheiro
29,Flávio,bembo,27,M,"1,66m",3500.0,Professor
30,Augusto,Mezenga,27,M,"1,62m",4500.0,Engenheiro
31,Pedro,Berdinatz,29,M,"1,72m",3500.0,Editor
32,Lara,Santos,28,Feminino,"1,7m",5000.0,Engenheiro
33,Pedro,Souza,35,M,"1,72m",5000.0,Engenheiro
34,Pedro,Souza,35,M,"1,72m",5000.0,Engenheiro
35,esta tabela termina bem aqui,NaN,NaN,NaN,NaN,NaN,NaN

**Skipirown:** O parâmetro skiprows na função pd.read_csv do Pandas serve para ignorar um determinado número de linhas ao importar um arquivo CSV. Ele permite que você exclua linhas indesejadas, como cabeçalhos não informativos, linhas em branco ou comentários, antes de converter o arquivo em um DataFrame.

Há diversas maneiras de utilizar o skiprows:

**Inteiro:** Passando um inteiro como valor, você indica a quantidade de linhas a serem ignoradas a partir do início do arquivo. Por exemplo, skiprows=2 ignoraria as duas primeiras linhas.

**Lista de inteiros:** Você pode fornecer uma lista de números de linhas específicos a serem ignoradas. Por exemplo, skiprows=[1,3] ignoraria a segunda e a quarta linha.

**Função:** Você pode passar uma função que recebe um index como argumento e retorna True para as linhas que devem ser ignoradas. Isso permite filtrar as linhas com base em critérios mais complexos.

**None (valor padrão)**: Se não for especificado, o Pandas assume que a primeira linha do arquivo é o cabeçalho e a lê como índices das colunas.
No seu exemplo específico, skiprows=None significa que nenhuma linha será ignorada e o Pandas lerá todas as linhas do arquivo.

Aqui estão alguns motivos para usar o skiprows:

**Limpar o cabeçalho:** Se o arquivo possui um cabeçalho não informativo ou incorreto, você pode ignorá-lo para evitar erros de parsing.
Remover linhas vazias ou comentários: Linhas vazias ou comentários podem atrapalhar a análise de dados.

**Ignorar introduções ou footers:**  Alguns arquivos possuem introduções ou footers com informações não relevantes para a análise.
Espero que isso esclareça o significado e o uso do parâmetro skiprows do Pandas. Se você tiver mais dúvidas, não hesite em perguntar!

In [5]:
#eliminamos a última linha
dataset.drop(dataset.index[-1], inplace=True)
dataset.tail()

       nome  sobrenome idade      sexo altura  salario_mensal   profissão
30  Augusto    Mezenga    27         M  1,62m          4500.0  Engenheiro
31    Pedro  Berdinatz    29         M  1,72m          3500.0      Editor
32     Lara     Santos    28  Feminino   1,7m          5000.0  Engenheiro
33    Pedro      Souza    35         M  1,72m          5000.0  Engenheiro
34    Pedro      Souza    35         M  1,72m          5000.0  Engenheiro

## 3.2 Alterando nome de coluna

In [6]:
## Vamos alterar a coluna profissão para profissao
dataset.rename(columns={'profissão': 'profissao'}, inplace=True)

In [7]:
dataset.head()

      nome sobrenome idade sexo altura  salario_mensal   profissao
0     João     Silva    30    M  1,64m          7000.0  Engenheiro
1     Lara     bembo    29    F  1,64m          3500.0      Músico
2    Pedro     bembo    35    M  1,67m             NaN    Advogado
3   Monica    Santos    28    F  1,66m          3500.0      Músico
4  Larissa  Ferreira    31    F   1,8m          3500.0   Professor

## 3.3 Missing e Alterações/ Criações de campos

In [8]:
dataset.isna()

     nome  sobrenome  idade   sexo  altura  salario_mensal  profissao
0   False      False  False  False   False           False      False
1   False      False  False  False   False           False      False
2   False      False  False  False   False            True      False
3   False      False  False  False   False           False      False
4   False      False  False  False   False           False      False
5   False      False  False  False   False           False      False
6   False      False  False  False   False           False      False
7   False      False  False  False   False           False      False
8   False      False  False  False   False           False      False
9   False      False  False  False   False           False      False
10  False      False  False  False   False            True      False
11  False      False  False  False   False           False      False
12  False      False  False  False   False           False      False
13  False      False  False  False   False           False      False
14  False      False  False  False   False           False      False
15  False      False  False  False   False           False      False
16  False      False  False  False   False           False      False
17  False      False  False  False   False           False      False
18  False      False  False  False   False            True      False
19  False      False  False  False   False           False      False
20  False      False  False  False   False           False      False
21  False      False  False  False   False           False      False
22  False      False  False  False   False           False      False
23  False      False   True   True    True           False      False
24  False      False  False  False   False           False      False
25  False      False  False  False   False           False      False
26  False      False  False  False   False           False      False
27  False      False  False  False   False           False      False
28  False      False  False  False   False           False      False
29  False      False  False  False   False           False      False
30  False      False  False  False   False           False      False
31  False      False  False  False   False           False      False
32  False      False  False  False   False           False      False
33  False      False  False  False   False           False      False
34  False      False  False  False   False           False      False

In [9]:
# contagem de missing por coluna
dataset.isna().sum()

nome              0
sobrenome         0
idade             1
sexo              1
altura            1
salario_mensal    3
profissao         0
dtype: int64

In [10]:
# contagem de nao-missing por coluna
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nome            35 non-null     object
 1   sobrenome       35 non-null     object
 2   idade           34 non-null     object
 3   sexo            34 non-null     object
 4   altura          34 non-null     object
 5   salario_mensal  32 non-null     float64
 6   profissao       35 non-null     object
dtypes: float64(1), object(6)
memory usage: 2.0+ KB

In [11]:
dataset[pd.isna(dataset['salario_mensal'])] # filtrar linhas em que salario_mensal é missing

      nome sobrenome idade sexo altura  salario_mensal profissao
2    Pedro     bembo    35    M  1,67m             NaN  Advogado
10  Monica  Ferreira    30    F  1,62m             NaN    Editor
18   Pedro     Souza    29    M  1,64m             NaN    Editor

### Preencher missing com valores

In [12]:
# vamos preencher com o valor correto
dataset.loc[dataset.index == 23, 'sexo'] = 'M'
dataset.loc[dataset.index == 32, 'sexo'] = 'F'

dataset

       nome  sobrenome    idade sexo altura  salario_mensal   profissao
0      João      Silva       30    M  1,64m          7000.0  Engenheiro
1      Lara      bembo       29    F  1,64m          3500.0      Músico
2     Pedro      bembo       35    M  1,67m             NaN    Advogado
3    Monica     Santos       28    F  1,66m          3500.0      Músico
4   Larissa   Ferreira       31    F   1,8m          3500.0   Professor
5      Lara      bembo       30    F  1,62m          7000.0  Engenheiro
6     Pedro       Lima       35    M  1,65m          7000.0  Engenheiro
7    Marcos       Lima       45    M  1,64m          4500.0  Engenheiro
8       Ana      Souza       27    F  1,75m          6000.0   Professor
9      José      bembo       35    M   1,9m          3500.0      Editor
10   Monica   Ferreira       30    F  1,62m             NaN      Editor
11      Ana     lokuto       27    F  1,67m          5000.0    Advogado
12   Jurema      Silva       32    F  1,65m          3500.0    Advogado
13    Pedro       Lima       34    M   1,7m          4500.0      Editor
14   Flávio      Silva       31    M  1,64m          3500.0  Engenheiro
15    André   Ferreira       35    M  1,72m          6000.0  Engenheiro
16     José   Ferreira       45    M  1,72m          4500.0      Músico
17    Pedro      bembo       30    M  1,69m          3500.0      Músico
18    Pedro      Souza       29    M  1,64m             NaN      Editor
19  Augusto     lokuto       40    M  1,66m          6000.0      Músico
20     José     Santos       40    M  1,66m          7000.0      Editor
21   Flávio      Souza       35    M  1,69m          7000.0    Advogado
22      Ana       Lima       29    F  1,64m          5000.0   Professor
23   Flávio      Souza      NaN    M    NaN          7000.0      Músico
24   Flávio      Souza       45    M  1,64m          7000.0      Músico
25    Pedro     lokuto       29    M  1,67m          4500.0   Professor
26   Monica       Lima       32    F  1,65m          6000.0  Engenheiro
27   Monica      bembo  34 anos    F  1,66m          7000.0   Professor
28    Joana   Ferreira       31    F  1,75m          5000.0  Engenheiro
29   Flávio      bembo       27    M  1,66m          3500.0   Professor
30  Augusto    Mezenga       27    M  1,62m          4500.0  Engenheiro
31    Pedro  Berdinatz       29    M  1,72m          3500.0      Editor
32     Lara     Santos       28    F   1,7m          5000.0  Engenheiro
33    Pedro      Souza       35    M  1,72m          5000.0  Engenheiro
34    Pedro      Souza       35    M  1,72m          5000.0  Engenheiro

In [13]:
# vamos preencher com o valor correto
dataset.loc[dataset.index == 2, 'salario_mensal'] = 5000
dataset.loc[dataset.index == 10, 'salario_mensal'] = 3500
dataset.loc[dataset.index == 18, 'salario_mensal'] = 3500

dataset.head(19)

       nome sobrenome idade sexo altura  salario_mensal   profissao
0      João     Silva    30    M  1,64m          7000.0  Engenheiro
1      Lara     bembo    29    F  1,64m          3500.0      Músico
2     Pedro     bembo    35    M  1,67m          5000.0    Advogado
3    Monica    Santos    28    F  1,66m          3500.0      Músico
4   Larissa  Ferreira    31    F   1,8m          3500.0   Professor
5      Lara     bembo    30    F  1,62m          7000.0  Engenheiro
6     Pedro      Lima    35    M  1,65m          7000.0  Engenheiro
7    Marcos      Lima    45    M  1,64m          4500.0  Engenheiro
8       Ana     Souza    27    F  1,75m          6000.0   Professor
9      José     bembo    35    M   1,9m          3500.0      Editor
10   Monica  Ferreira    30    F  1,62m          3500.0      Editor
11      Ana    lokuto    27    F  1,67m          5000.0    Advogado
12   Jurema     Silva    32    F  1,65m          3500.0    Advogado
13    Pedro      Lima    34    M   1,7m          4500.0      Editor
14   Flávio     Silva    31    M  1,64m          3500.0  Engenheiro
15    André  Ferreira    35    M  1,72m          6000.0  Engenheiro
16     José  Ferreira    45    M  1,72m          4500.0      Músico
17    Pedro     bembo    30    M  1,69m          3500.0      Músico
18    Pedro     Souza    29    M  1,64m          3500.0      Editor

### Retirar texto a mais

In [14]:
dataset['idade'] # vamos preencher o missing com a média geral e retirar a palavra anos.
#depois transformar o data type em int.

0          30
1          29
2          35
3          28
4          31
5          30
6          35
7          45
8          27
9          35
10         30
11         27
12         32
13         34
14         31
15         35
16         45
17         30
18         29
19         40
20         40
21         35
22         29
23        NaN
24         45
25         29
26         32
27    34 anos
28         31
29         27
30         27
31         29
32         28
33         35
34         35
Name: idade, dtype: object

In [15]:
dataset['idade'] = dataset['idade'].replace(' anos', '', regex=True)
dataset['idade']

0      30
1      29
2      35
3      28
4      31
5      30
6      35
7      45
8      27
9      35
10     30
11     27
12     32
13     34
14     31
15     35
16     45
17     30
18     29
19     40
20     40
21     35
22     29
23    NaN
24     45
25     29
26     32
27     34
28     31
29     27
30     27
31     29
32     28
33     35
34     35
Name: idade, dtype: object

In [16]:
#fazer para altura tbm
dataset.head()

      nome sobrenome idade sexo altura  salario_mensal   profissao
0     João     Silva    30    M  1,64m          7000.0  Engenheiro
1     Lara     bembo    29    F  1,64m          3500.0      Músico
2    Pedro     bembo    35    M  1,67m          5000.0    Advogado
3   Monica    Santos    28    F  1,66m          3500.0      Músico
4  Larissa  Ferreira    31    F   1,8m          3500.0   Professor

In [17]:
dataset['altura'] = dataset['altura'].replace('m', '', regex = True)
dataset['altura'] = dataset['altura'].replace(',', '.', regex = True)
dataset.head()

      nome sobrenome idade sexo altura  salario_mensal   profissao
0     João     Silva    30    M   1.64          7000.0  Engenheiro
1     Lara     bembo    29    F   1.64          3500.0      Músico
2    Pedro     bembo    35    M   1.67          5000.0    Advogado
3   Monica    Santos    28    F   1.66          3500.0      Músico
4  Larissa  Ferreira    31    F    1.8          3500.0   Professor

## 3.4 Preencher missing com média

In [18]:
#verificar se o campo idade está numerico
dataset['idade'].dtypes #esta como objeto

dtype('O')

In [19]:
#alterar objeto para int
#dataset['idade'] = dataset['idade'].astype(int)
# o erro acontece pois existe um campo nulo

In [20]:
#converter valor nulo para 0
dataset['idade'] = dataset['idade'].fillna(0)
dataset.dtypes

nome               object
sobrenome          object
idade              object
sexo               object
altura             object
salario_mensal    float64
profissao          object
dtype: object

In [21]:
#converter objeto para int em 'idade'
dataset['idade'] = dataset['idade'].astype(int)
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nome            35 non-null     object
 1   sobrenome       35 non-null     object
 2   idade           35 non-null     int64
 3   sexo            35 non-null     object
 4   altura          34 non-null     object
 5   salario_mensal  35 non-null     float64
 6   profissao       35 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.0+ KB

In [22]:
dataset['idade'] == 0 # descobre onde está o registro

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23     True
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
Name: idade, dtype: bool

In [23]:
# localiza e altera o registro 23 para a média
dataset.loc[23, 'idade'] = int(dataset['idade'].mean())
dataset['idade']

0     30
1     29
2     35
3     28
4     31
5     30
6     35
7     45
8     27
9     35
10    30
11    27
12    32
13    34
14    31
15    35
16    45
17    30
18    29
19    40
20    40
21    35
22    29
23    31
24    45
25    29
26    32
27    34
28    31
29    27
30    27
31    29
32    28
33    35
34    35
Name: idade, dtype: int64

## 3.5 Eliminando nulos com DROP

In [24]:
# calcula o número total de valores ausentes em todas as colunas
dataset.isna().sum()

nome              0
sobrenome         0
idade             0
sexo              0
altura            1
salario_mensal    0
profissao         0
dtype: int64

In [25]:
# retorna falso quando contem valores e verdadeiro valores nulos
dataset.isna()

     nome  sobrenome  idade   sexo  altura  salario_mensal  profissao
0   False      False  False  False   False           False      False
1   False      False  False  False   False           False      False
2   False      False  False  False   False           False      False
3   False      False  False  False   False           False      False
4   False      False  False  False   False           False      False
5   False      False  False  False   False           False      False
6   False      False  False  False   False           False      False
7   False      False  False  False   False           False      False
8   False      False  False  False   False           False      False
9   False      False  False  False   False           False      False
10  False      False  False  False   False           False      False
11  False      False  False  False   False           False      False
12  False      False  False  False   False           False      False
13  False      False  False  False   False           False      False
14  False      False  False  False   False           False      False
15  False      False  False  False   False           False      False
16  False      False  False  False   False           False      False
17  False      False  False  False   False           False      False
18  False      False  False  False   False           False      False
19  False      False  False  False   False           False      False
20  False      False  False  False   False           False      False
21  False      False  False  False   False           False      False
22  False      False  False  False   False           False      False
23  False      False  False  False    True           False      False
24  False      False  False  False   False           False      False
25  False      False  False  False   False           False      False
26  False      False  False  False   False           False      False
27  False      False  False  False   False           False      False
28  False      False  False  False   False           False      False
29  False      False  False  False   False           False      False
30  False      False  False  False   False           False      False
31  False      False  False  False   False           False      False
32  False      False  False  False   False           False      False
33  False      False  False  False   False           False      False
34  False      False  False  False   False           False      False

In [26]:
#elimina as linhas com valores ausentes, o 23 deve sair
dataset.dropna(inplace=True)
dataset

       nome  sobrenome  idade sexo altura  salario_mensal   profissao
0      João      Silva     30    M   1.64          7000.0  Engenheiro
1      Lara      bembo     29    F   1.64          3500.0      Músico
2     Pedro      bembo     35    M   1.67          5000.0    Advogado
3    Monica     Santos     28    F   1.66          3500.0      Músico
4   Larissa   Ferreira     31    F    1.8          3500.0   Professor
5      Lara      bembo     30    F   1.62          7000.0  Engenheiro
6     Pedro       Lima     35    M   1.65          7000.0  Engenheiro
7    Marcos       Lima     45    M   1.64          4500.0  Engenheiro
8       Ana      Souza     27    F   1.75          6000.0   Professor
9      José      bembo     35    M    1.9          3500.0      Editor
10   Monica   Ferreira     30    F   1.62          3500.0      Editor
11      Ana     lokuto     27    F   1.67          5000.0    Advogado
12   Jurema      Silva     32    F   1.65          3500.0    Advogado
13    Pedro       Lima     34    M    1.7          4500.0      Editor
14   Flávio      Silva     31    M   1.64          3500.0  Engenheiro
15    André   Ferreira     35    M   1.72          6000.0  Engenheiro
16     José   Ferreira     45    M   1.72          4500.0      Músico
17    Pedro      bembo     30    M   1.69          3500.0      Músico
18    Pedro      Souza     29    M   1.64          3500.0      Editor
19  Augusto     lokuto     40    M   1.66          6000.0      Músico
20     José     Santos     40    M   1.66          7000.0      Editor
21   Flávio      Souza     35    M   1.69          7000.0    Advogado
22      Ana       Lima     29    F   1.64          5000.0   Professor
24   Flávio      Souza     45    M   1.64          7000.0      Músico
25    Pedro     lokuto     29    M   1.67          4500.0   Professor
26   Monica       Lima     32    F   1.65          6000.0  Engenheiro
27   Monica      bembo     34    F   1.66          7000.0   Professor
28    Joana   Ferreira     31    F   1.75          5000.0  Engenheiro
29   Flávio      bembo     27    M   1.66          3500.0   Professor
30  Augusto    Mezenga     27    M   1.62          4500.0  Engenheiro
31    Pedro  Berdinatz     29    M   1.72          3500.0      Editor
32     Lara     Santos     28    F    1.7          5000.0  Engenheiro
33    Pedro      Souza     35    M   1.72          5000.0  Engenheiro
34    Pedro      Souza     35    M   1.72          5000.0  Engenheiro

## 3.4 Linhas duplicadas

In [27]:
# Retorna as linhas duplicadas
dataset.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34     True
dtype: bool

In [28]:
# Soma o número de linhas duplicadas
dataset.duplicated().sum()

1

In [29]:
#exclui a linha duplicada
dataset.drop_duplicates(inplace = True) # o True precisa estar em maiúsculo para funcionar
dataset.tail()

       nome  sobrenome  idade sexo altura  salario_mensal   profissao
29   Flávio      bembo     27    M   1.66          3500.0   Professor
30  Augusto    Mezenga     27    M   1.62          4500.0  Engenheiro
31    Pedro  Berdinatz     29    M   1.72          3500.0      Editor
32     Lara     Santos     28    F    1.7          5000.0  Engenheiro
33    Pedro      Souza     35    M   1.72          5000.0  Engenheiro

In [30]:
dataset.duplicated().sum()

0

## Alterar tipo de dado na coluna

In [31]:
dataset.info() # vamos alterar a altura, de objeto para float

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33 entries, 0 to 33
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nome            33 non-null     object
 1   sobrenome       33 non-null     object
 2   idade           33 non-null     int64
 3   sexo            33 non-null     object
 4   altura          33 non-null     object
 5   salario_mensal  33 non-null     float64
 6   profissao       33 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.1+ KB

In [32]:
dataset['altura'] = dataset['altura'].astype(float)
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33 entries, 0 to 33
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nome            33 non-null     object
 1   sobrenome       33 non-null     object
 2   idade           33 non-null     int64
 3   sexo            33 non-null     object
 4   altura          33 non-null     float64
 5   salario_mensal  33 non-null     float64
 6   profissao       33 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 2.1+ KB

# 2. Informações sobre o Dataset

In [33]:
dataset.shape
# Indica que temos 33 linhas e 7 colunas

(33, 7)

In [34]:
dataset.shape[0]
# mostra apenas o número de linhas

33

In [35]:
dataset.shape[1]
# mostra apenas o número de colunas

7

In [36]:
dataset.columns

Index(['nome', 'sobrenome', 'idade', 'sexo', 'altura', 'salario_mensal',
       'profissao'],
      dtype='object')

In [37]:
# mostra a quantidade de linhas
len(dataset)

33

In [38]:
#  retorna o número de valores únicos em uma coluna ou DataFrame
dataset.nunique()

nome              13
sobrenome          9
idade             10
sexo               2
altura            11
salario_mensal     5
profissao          5
dtype: int64

In [39]:
#retorna o total de valores únicos de uma só coluna
dataset['profissao'].nunique()

5

In [40]:
#contagem e todos os valores
dataset['salario_mensal'].value_counts()

3500.0    11
7000.0     7
5000.0     6
4500.0     5
6000.0     4
Name: salario_mensal, dtype: int64

In [41]:
#os valores também podem ser normalizados para expressar porcentagem
dataset['salario_mensal'].value_counts(normalize = True)

3500.0    0.333333
7000.0    0.212121
5000.0    0.181818
4500.0    0.151515
6000.0    0.121212
Name: salario_mensal, dtype: float64

In [42]:
dataset['profissao'].values

array(['Engenheiro', 'Músico', 'Advogado', 'Músico', 'Professor',
       'Engenheiro', 'Engenheiro', 'Engenheiro', 'Professor', 'Editor',
       'Editor', 'Advogado', 'Advogado', 'Editor', 'Engenheiro',
       'Engenheiro', 'Músico', 'Músico', 'Editor', 'Músico', 'Editor',
       'Advogado', 'Professor', 'Músico', 'Professor', 'Engenheiro',
       'Professor', 'Engenheiro', 'Professor', 'Engenheiro', 'Editor',
       'Engenheiro', 'Engenheiro'], dtype=object)

In [43]:
dataset['profissao'].dtype

dtype('O')

In [44]:
## Visualizar as primeiras linhas. O espaco (), em branco indica as primeiras 5 linhas.
## Com número indica as primeiras linhas, no caso abaixo até 8
dataset.head()

      nome sobrenome  idade sexo  altura  salario_mensal   profissao
0     João     Silva     30    M    1.64          7000.0  Engenheiro
1     Lara     bembo     29    F    1.64          3500.0      Músico
2    Pedro     bembo     35    M    1.67          5000.0    Advogado
3   Monica    Santos     28    F    1.66          3500.0      Músico
4  Larissa  Ferreira     31    F    1.80          3500.0   Professor

In [45]:
dataset.head(8)

      nome sobrenome  idade sexo  altura  salario_mensal   profissao
0     João     Silva     30    M    1.64          7000.0  Engenheiro
1     Lara     bembo     29    F    1.64          3500.0      Músico
2    Pedro     bembo     35    M    1.67          5000.0    Advogado
3   Monica    Santos     28    F    1.66          3500.0      Músico
4  Larissa  Ferreira     31    F    1.80          3500.0   Professor
5     Lara     bembo     30    F    1.62          7000.0  Engenheiro
6    Pedro      Lima     35    M    1.65          7000.0  Engenheiro
7   Marcos      Lima     45    M    1.64          4500.0  Engenheiro

In [46]:
# Para ver as ultimas 5 linhas no final do arquivo
dataset.tail()

       nome  sobrenome  idade sexo  altura  salario_mensal   profissao
29   Flávio      bembo     27    M    1.66          3500.0   Professor
30  Augusto    Mezenga     27    M    1.62          4500.0  Engenheiro
31    Pedro  Berdinatz     29    M    1.72          3500.0      Editor
32     Lara     Santos     28    F    1.70          5000.0  Engenheiro
33    Pedro      Souza     35    M    1.72          5000.0  Engenheiro

In [47]:
#use o display para visualizar os dois juntos
display(dataset.head())
display(dataset.tail())

      nome sobrenome  idade sexo  altura  salario_mensal   profissao
0     João     Silva     30    M    1.64          7000.0  Engenheiro
1     Lara     bembo     29    F    1.64          3500.0      Músico
2    Pedro     bembo     35    M    1.67          5000.0    Advogado
3   Monica    Santos     28    F    1.66          3500.0      Músico
4  Larissa  Ferreira     31    F    1.80          3500.0   Professor

       nome  sobrenome  idade sexo  altura  salario_mensal   profissao
29   Flávio      bembo     27    M    1.66          3500.0   Professor
30  Augusto    Mezenga     27    M    1.62          4500.0  Engenheiro
31    Pedro  Berdinatz     29    M    1.72          3500.0      Editor
32     Lara     Santos     28    F    1.70          5000.0  Engenheiro
33    Pedro      Souza     35    M    1.72          5000.0  Engenheiro

In [48]:
#visualiza uma coluna específica
dataset['nome']

0        João
1        Lara
2       Pedro
3      Monica
4     Larissa
5        Lara
6       Pedro
7      Marcos
8         Ana
9        José
10     Monica
11        Ana
12     Jurema
13      Pedro
14     Flávio
15      André
16       José
17      Pedro
18      Pedro
19    Augusto
20       José
21     Flávio
22        Ana
24     Flávio
25      Pedro
26     Monica
27     Monica
28      Joana
29     Flávio
30    Augusto
31      Pedro
32       Lara
33      Pedro
Name: nome, dtype: object

In [49]:
# visualiza apenas as colunas determinadas abaixo:
dataset[['nome', 'sobrenome']]

       nome  sobrenome
0      João      Silva
1      Lara      bembo
2     Pedro      bembo
3    Monica     Santos
4   Larissa   Ferreira
5      Lara      bembo
6     Pedro       Lima
7    Marcos       Lima
8       Ana      Souza
9      José      bembo
10   Monica   Ferreira
11      Ana     lokuto
12   Jurema      Silva
13    Pedro       Lima
14   Flávio      Silva
15    André   Ferreira
16     José   Ferreira
17    Pedro      bembo
18    Pedro      Souza
19  Augusto     lokuto
20     José     Santos
21   Flávio      Souza
22      Ana       Lima
24   Flávio      Souza
25    Pedro     lokuto
26   Monica       Lima
27   Monica      bembo
28    Joana   Ferreira
29   Flávio      bembo
30  Augusto    Mezenga
31    Pedro  Berdinatz
32     Lara     Santos
33    Pedro      Souza

# Índices da tabela

In [50]:
#seleciona as linhas de 5:9 e a coluna específica
dataset.loc[5:9, 'nome']

5      Lara
6     Pedro
7    Marcos
8       Ana
9      José
Name: nome, dtype: object

In [51]:
#de 0:5 esta definindo o número de linhas e de 0:4 o número de colunas
# Para isso usa-se o ILOC
dataset.iloc[0:5, 0:4]

      nome sobrenome  idade sexo
0     João     Silva     30    M
1     Lara     bembo     29    F
2    Pedro     bembo     35    M
3   Monica    Santos     28    F
4  Larissa  Ferreira     31    F

In [52]:
dataset.index

# Mostra que o índice comeca com 0, possui 34 linhas, numeradas de 0 a 33 e é incrementado de 1 em 1.

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
           dtype='int64')

Se quiser estabelecer uma coluna como índice é só usar set_index, por exemplo:

df.set_index('nome da coluna') # para uma coluna
df.set_index(['nome da coluna 1', 'nome da coluna 2', ..., 'nome da coluna n'] # para varias colunas
df.set_index([pd.index)[1,2,3,4...],'nome do indice') # pra criar um indice novo do zero

---

In [53]:
# Seleciona a linha específica, no caso a linha dentro do índice 3
dataset.loc[3]

nome              Monica
sobrenome         Santos
idade                 28
sexo                   F
altura              1.66
salario_mensal    3500.0
profissao         Músico
Name: 3, dtype: object

In [54]:
dataset.loc[0:3]

     nome sobrenome  idade sexo  altura  salario_mensal   profissao
0    João     Silva     30    M    1.64          7000.0  Engenheiro
1    Lara     bembo     29    F    1.64          3500.0      Músico
2   Pedro     bembo     35    M    1.67          5000.0    Advogado
3  Monica    Santos     28    F    1.66          3500.0      Músico

### Zera o índice
Nós temos um índice que foi 'dropado', o 23.
Vamos zerar novamente o índice.

In [55]:
dataset.reset_index(drop=False, inplace=True)

In [56]:
dataset

    index     nome  sobrenome  idade sexo  altura  salario_mensal   profissao
0       0     João      Silva     30    M    1.64          7000.0  Engenheiro
1       1     Lara      bembo     29    F    1.64          3500.0      Músico
2       2    Pedro      bembo     35    M    1.67          5000.0    Advogado
3       3   Monica     Santos     28    F    1.66          3500.0      Músico
4       4  Larissa   Ferreira     31    F    1.80          3500.0   Professor
5       5     Lara      bembo     30    F    1.62          7000.0  Engenheiro
6       6    Pedro       Lima     35    M    1.65          7000.0  Engenheiro
7       7   Marcos       Lima     45    M    1.64          4500.0  Engenheiro
8       8      Ana      Souza     27    F    1.75          6000.0   Professor
9       9     José      bembo     35    M    1.90          3500.0      Editor
10     10   Monica   Ferreira     30    F    1.62          3500.0      Editor
11     11      Ana     lokuto     27    F    1.67          5000.0    Advogado
12     12   Jurema      Silva     32    F    1.65          3500.0    Advogado
13     13    Pedro       Lima     34    M    1.70          4500.0      Editor
14     14   Flávio      Silva     31    M    1.64          3500.0  Engenheiro
15     15    André   Ferreira     35    M    1.72          6000.0  Engenheiro
16     16     José   Ferreira     45    M    1.72          4500.0      Músico
17     17    Pedro      bembo     30    M    1.69          3500.0      Músico
18     18    Pedro      Souza     29    M    1.64          3500.0      Editor
19     19  Augusto     lokuto     40    M    1.66          6000.0      Músico
20     20     José     Santos     40    M    1.66          7000.0      Editor
21     21   Flávio      Souza     35    M    1.69          7000.0    Advogado
22     22      Ana       Lima     29    F    1.64          5000.0   Professor
23     24   Flávio      Souza     45    M    1.64          7000.0      Músico
24     25    Pedro     lokuto     29    M    1.67          4500.0   Professor
25     26   Monica       Lima     32    F    1.65          6000.0  Engenheiro
26     27   Monica      bembo     34    F    1.66          7000.0   Professor
27     28    Joana   Ferreira     31    F    1.75          5000.0  Engenheiro
28     29   Flávio      bembo     27    M    1.66          3500.0   Professor
29     30  Augusto    Mezenga     27    M    1.62          4500.0  Engenheiro
30     31    Pedro  Berdinatz     29    M    1.72          3500.0      Editor
31     32     Lara     Santos     28    F    1.70          5000.0  Engenheiro
32     33    Pedro      Souza     35    M    1.72          5000.0  Engenheiro

## Filtros

In [57]:
dataset.idade.value_counts()

35    6
29    5
30    4
27    4
31    3
45    3
28    2
32    2
34    2
40    2
Name: idade, dtype: int64

In [58]:
# note que não funciona, isso pq nosso indice comeca com 3 após as alteracões
dataset.loc[1]

index                  1
nome                Lara
sobrenome          bembo
idade                 29
sexo                   F
altura              1.64
salario_mensal    3500.0
profissao         Músico
Name: 1, dtype: object

In [59]:
#agora funciona
dataset.loc[3]

index                  3
nome              Monica
sobrenome         Santos
idade                 28
sexo                   F
altura              1.66
salario_mensal    3500.0
profissao         Músico
Name: 3, dtype: object

In [60]:
#vamos zerar o índice novamente
dataset.reset_index(drop=True, inplace=True)

dataset.head()

   index     nome sobrenome  idade sexo  altura  salario_mensal   profissao
0      0     João     Silva     30    M    1.64          7000.0  Engenheiro
1      1     Lara     bembo     29    F    1.64          3500.0      Músico
2      2    Pedro     bembo     35    M    1.67          5000.0    Advogado
3      3   Monica    Santos     28    F    1.66          3500.0      Músico
4      4  Larissa  Ferreira     31    F    1.80          3500.0   Professor

In [61]:
#agora a linha volta a funcionar, veja:
dataset.loc[1]

index                  1
nome                Lara
sobrenome          bembo
idade                 29
sexo                   F
altura              1.64
salario_mensal    3500.0
profissao         Músico
Name: 1, dtype: object

In [62]:
dataset.loc[1:5]

   index     nome sobrenome  idade sexo  altura  salario_mensal   profissao
1      1     Lara     bembo     29    F    1.64          3500.0      Músico
2      2    Pedro     bembo     35    M    1.67          5000.0    Advogado
3      3   Monica    Santos     28    F    1.66          3500.0      Músico
4      4  Larissa  Ferreira     31    F    1.80          3500.0   Professor
5      5     Lara     bembo     30    F    1.62          7000.0  Engenheiro

# 4. Estatística básica

In [63]:
dataset.describe()

           index      idade     altura  salario_mensal
count  33.000000  33.000000  33.000000        33.00000
mean   16.303030  32.696970   1.680606      4969.69697
std    10.045163   5.235007   0.057822      1345.93946
min     0.000000  27.000000   1.620000      3500.00000
25%     8.000000  29.000000   1.640000      3500.00000
50%    16.000000  31.000000   1.660000      5000.00000
75%    25.000000  35.000000   1.700000      6000.00000
max    33.000000  45.000000   1.900000      7000.00000

In [64]:
#.sum(): calcula a soma dos valores em uma coluna ou DataFrame.
dataset['salario_mensal'].sum()

164000.0

In [65]:
#.mean(): calcula a média dos valores em uma coluna ou DataFrame.
dataset['salario_mensal'].mean()

4969.69696969697

In [66]:
#.median(): calcula a mediana dos valores em uma coluna ou DataFrame.
dataset['salario_mensal'].median()

5000.0

In [67]:
#.std(): calcula o desvio padrão dos valores em uma coluna ou DataFrame.
dataset['salario_mensal'].std()

1345.9394601181104

# 5. Manipulando dados

In [68]:
dataset['salario_mensal']

0     7000.0
1     3500.0
2     5000.0
3     3500.0
4     3500.0
5     7000.0
6     7000.0
7     4500.0
8     6000.0
9     3500.0
10    3500.0
11    5000.0
12    3500.0
13    4500.0
14    3500.0
15    6000.0
16    4500.0
17    3500.0
18    3500.0
19    6000.0
20    7000.0
21    7000.0
22    5000.0
23    7000.0
24    4500.0
25    6000.0
26    7000.0
27    5000.0
28    3500.0
29    4500.0
30    3500.0
31    5000.0
32    5000.0
Name: salario_mensal, dtype: float64

In [69]:
dataset.loc[(dataset['idade'] >= 35)]

    index     nome sobrenome  idade sexo  altura  salario_mensal   profissao
2       2    Pedro     bembo     35    M    1.67          5000.0    Advogado
6       6    Pedro      Lima     35    M    1.65          7000.0  Engenheiro
7       7   Marcos      Lima     45    M    1.64          4500.0  Engenheiro
9       9     José     bembo     35    M    1.90          3500.0      Editor
15     15    André  Ferreira     35    M    1.72          6000.0  Engenheiro
16     16     José  Ferreira     45    M    1.72          4500.0      Músico
19     19  Augusto    lokuto     40    M    1.66          6000.0      Músico
20     20     José    Santos     40    M    1.66          7000.0      Editor
21     21   Flávio     Souza     35    M    1.69          7000.0    Advogado
23     24   Flávio     Souza     45    M    1.64          7000.0      Músico
32     33    Pedro     Souza     35    M    1.72          5000.0  Engenheiro

## Agrupamento

In [70]:
dataset.loc[(dataset['idade'] >= 35) & (dataset['altura'] > 1.65)]

    index     nome sobrenome  idade sexo  altura  salario_mensal   profissao
2       2    Pedro     bembo     35    M    1.67          5000.0    Advogado
9       9     José     bembo     35    M    1.90          3500.0      Editor
15     15    André  Ferreira     35    M    1.72          6000.0  Engenheiro
16     16     José  Ferreira     45    M    1.72          4500.0      Músico
19     19  Augusto    lokuto     40    M    1.66          6000.0      Músico
20     20     José    Santos     40    M    1.66          7000.0      Editor
21     21   Flávio     Souza     35    M    1.69          7000.0    Advogado
32     33    Pedro     Souza     35    M    1.72          5000.0  Engenheiro